version: 2
jobs:
  build:
    docker:
      - image: circleci/node
      - image: redis
      - image: memcached
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Ensure Test Parity
          command: |
            chmod +x yes.sh
            ./yes.sh
