version: 2
resource_class: large
jobs:
  build:
    docker:
      - image: cimg/go:1.16.4
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Ensure Test Parity
          command: |
            chmod +x yes.sh
            ./yes.sh
   
