version: 2
jobs:
  build:
    docker:
      - image: circleci/node
      - image: redis
    steps:
      - checkout
      - run:
          name: Ensure Test Parity
          command: |
            chmod +x yes.sh
            ./yes.sh
